name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android-test:
    runs-on: self-hosted
    services:
      android-emulator:
        image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
        ports:
          - "5555:5555"
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11.0.4'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: android-emulator
        run: adb connect android-emulator:5555 && adb wait-for-device
