name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android-test:
    runs-on: ubuntu-latest
    services:
      service-name-1:
        image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
        ports:
           - 3001:3000
